Tintwentyseven/DoAnLapTrinhFE

.idea/vcs.xml, package-lock.json, package.json, src/App.js, src/componemts/ChatBox/index.js, src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css, src/componemts/CreateRoom/index.js, src/componemts/Header/index.js, src/componemts/InputMess/index.js, src/componemts/Login/index.js, src/componemts/ModalMember/index.js, src/componemts/Register/index.js, src/componemts/Test/index.js, src/componemts/UserList/index.js, src/firebase.js, src/pages/Home.js
Này là giao diện Chat của CookieChat
=> Giao dien chatroom

package-lock.json, package.json, src/App.js, src/componemts/ChatBox/index.js, src/componemts/ChatRoom/confetti.js, src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css, src/componemts/Login/index.js, src/componemts/Register/index.js, src/pages/Home.js, src/util/websocket.js
Kết nối WebSocket và gửi request dưới dạng JSON đến server thông qua kết nối WebSocket
=> Login bang api Login

src/componemts/ChatRoom/index.js
Tim phong dua tren api GET_USER_LIST va hien vai tro cua nguoi dung dựa vào API GET_ROOM_CHAT_MES
=> Find room and show role of user

src/App.js, src/componemts/Home/index.js, src/componemts/Home/style.css
Mọi người vào xem tui mới link trang home giới thiệu web chat nhá
=> ket noi trang home

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css
Them lua chon de chuyen sang light mode -> dark mode nham tang trai nghiem ve giao dien
=> them dark mode cho chatroom

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css
Hiển thị tin nhắn người dùng, phòng chat theo thứ tự thời gian
=> Hien tin nhan phong chat,nguoi dung

src/componemts/ChatRoom/index.js
Tăng thời gian trả về từ api lên 7h để có giá trị trùng với mốc thời gian hiện tại
=> Sua thoi gian nhan tin

src/componemts/ChatRoom/index.js
Sửa lỗi ở lần merge fix conflict #14 và thêm sự kiện tự động cuộn để khi xem tin nhắn mới nhất và đóng trang sẽ xóa dữ liệu localstorage
=> Sửa lỗi merge #14 và thêm sự kiện tự động cuộn, đóng trang

src/componemts/ChatRoom/index.js
mọi người vào xem chức năng tham gia phòng chat nhé
=> tham gia phong chat

src/componemts/ChatRoom/index.js
tui mới fix lại phần hiển thị phòng chat bên khung chat khi join vào phòng nhe mọi người
=> hien thi phong chat khi join

src/componemts/ChatRoom/index.js
dô xem tui fix lại chức năng tìm kiếm nhe mấy ní
=> tim kiem user

src/componemts/ChatRoom/index.js
Kiểm tra bằng regex nếu tin nhắn có url thì hiện trong thẻ a
=> Hiển thị tin nhắn định dạng url

src/componemts/ChatRoom/index.js
=> Tao avatar cho room

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css, src/componemts/Login/index.js
Lưu dữ liệu vào sessionStorage để khi mở tab khác và thực hiện đăng nhập vào tài khoản khác thì ko ảnh hưởng tới tài khoản ở tab ban đầu
=> Luu du lieu len sessionStorage de mo duoc nhieu tab

src/componemts/ChatRoom/index.js
Fix lỗi tên phòng đã tồn tại vẫn hiển thị trên khung người dùng
=> Fix lỗi tên phòng đã tồn tại vẫn hiển thị trên khung người dùng

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css
Cập nhập giao diện để hiện modal Change Avatar có 2 tab để đổi avatar cho người dùng đang đăng nhập hoặc phòng người dùng đó đã tạo
=> Cap nhap giao dien modal co tab cho change avatar

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css
Thêm tab để phân ra người dùng và nhóm , tạo tab cho chức năng create room và join room
=> Them tab cho user,room va tao tab cho create,join room

src/componemts/ChatRoom/index.js, src/componemts/Login/index.js
Đổi và cập nhập lại avatar cho người dùng đã đăng nhập vào
=> Doi avatar va cap nhap lai tren giao dien

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css
tui mới cập nhật phần kiểm tra trạng thái hoạt động mọi người xem thử nhé
=> kiem tra trang thai user

src/componemts/ChatRoom/index.js
Đổi avatar cho phòng mà người dùng đã tạo
=> Doi avatar cho phong moi va cu

package-lock.json, package.json, src/componemts/ChatRoom/index.js
Khi người dùng gửi link youtube thì sẽ có thể phát video đó trong khung chat
=> Cho phep phat video youtube trong khung chat

src/componemts/ChatRoom/index.js, src/componemts/ChatRoom/style.css, src/firebase.js
Sửa lỗi conflict gừi file ko thả icon và thu hồi tin nhắn được
=> Sửa lỗi conflict gừi file
